//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.26 at 11:52:13 a. m. CDT 
//


package com.banorte.ws.esb.reconciliaciones.ObtenerInventario.full.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banorte.ws.esb.reconciliaciones.ObtenerInventario.full.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObtenerInventarioFullTypeRequest_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliacionesbeta", "ObtenerInventarioFullTypeRequest");
    private final static QName _CadenaLGTreintaYDos_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliacionesbeta", "CadenaLGTreintaYDos");
    private final static QName _CadenaLGTreinta_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliacionesbeta", "CadenaLGTreinta");
    private final static QName _CadenaLGSesentaYCuatro_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliacionesbeta", "CadenaLGSesentaYCuatro");
    private final static QName _ObtenerInventarioFullTypeResponse_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliacionesbeta", "ObtenerInventarioFullTypeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banorte.ws.esb.reconciliaciones.ObtenerInventario.full.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerInventarioFullTypeResponse }
     * 
     */
    public ObtenerInventarioFullTypeResponse createObtenerInventarioFullTypeResponse() {
        return new ObtenerInventarioFullTypeResponse();
    }

    /**
     * Create an instance of {@link ObtenerInventarioFullTypeRequest }
     * 
     */
    public ObtenerInventarioFullTypeRequest createObtenerInventarioFullTypeRequest() {
        return new ObtenerInventarioFullTypeRequest();
    }

    /**
     * Create an instance of {@link ObtenerInventarioFullTypeResponse.Objetos.Objeto }
     * 
     */
    public ObtenerInventarioFullTypeResponse.Objetos.Objeto createObtenerInventarioFullTypeResponseObjetosObjeto() {
        return new ObtenerInventarioFullTypeResponse.Objetos.Objeto();
    }

    /**
     * Create an instance of {@link ObtenerInventarioFullTypeResponse.Objetos }
     * 
     */
    public ObtenerInventarioFullTypeResponse.Objetos createObtenerInventarioFullTypeResponseObjetos() {
        return new ObtenerInventarioFullTypeResponse.Objetos();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerInventarioFullTypeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliacionesbeta", name = "ObtenerInventarioFullTypeRequest")
    public JAXBElement<ObtenerInventarioFullTypeRequest> createObtenerInventarioFullTypeRequest(ObtenerInventarioFullTypeRequest value) {
        return new JAXBElement<ObtenerInventarioFullTypeRequest>(_ObtenerInventarioFullTypeRequest_QNAME, ObtenerInventarioFullTypeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliacionesbeta", name = "CadenaLGTreintaYDos")
    public JAXBElement<String> createCadenaLGTreintaYDos(String value) {
        return new JAXBElement<String>(_CadenaLGTreintaYDos_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliacionesbeta", name = "CadenaLGTreinta")
    public JAXBElement<String> createCadenaLGTreinta(String value) {
        return new JAXBElement<String>(_CadenaLGTreinta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliacionesbeta", name = "CadenaLGSesentaYCuatro")
    public JAXBElement<String> createCadenaLGSesentaYCuatro(String value) {
        return new JAXBElement<String>(_CadenaLGSesentaYCuatro_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerInventarioFullTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliacionesbeta", name = "ObtenerInventarioFullTypeResponse")
    public JAXBElement<ObtenerInventarioFullTypeResponse> createObtenerInventarioFullTypeResponse(ObtenerInventarioFullTypeResponse value) {
        return new JAXBElement<ObtenerInventarioFullTypeResponse>(_ObtenerInventarioFullTypeResponse_QNAME, ObtenerInventarioFullTypeResponse.class, null, value);
    }

}
