//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 12:51:02 a. m. CDT 
//


package com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObtenerObjetoFiltradaOutTypeResponse_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "ObtenerObjetoFiltradaOutTypeResponse");
    private final static QName _CadenaLGTreintaYDos_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGTreintaYDos");
    private final static QName _CadenaLGTreinta_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGTreinta");
    private final static QName _CadenaLGVeinte_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGVeinte");
    private final static QName _CadenaLGSesentaYCuatro_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGSesentaYCuatro");
    private final static QName _ObtenerObjetoFiltradaInTypeRequest_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "ObtenerObjetoFiltradaInTypeRequest");
    private final static QName _CadenaLGDoscientosCincuentaYSeis_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGDoscientosCincuentaYSeis");
    private final static QName _CadenaLGOcho_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGOcho");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutTypeResponse.Objetos.Objeto }
     * 
     */
    public ObtenerObjetoFiltradaOutTypeResponse.Objetos.Objeto createObtenerObjetoFiltradaOutTypeResponseObjetosObjeto() {
        return new ObtenerObjetoFiltradaOutTypeResponse.Objetos.Objeto();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutTypeResponse.Relaciones }
     * 
     */
    public ObtenerObjetoFiltradaOutTypeResponse.Relaciones createObtenerObjetoFiltradaOutTypeResponseRelaciones() {
        return new ObtenerObjetoFiltradaOutTypeResponse.Relaciones();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaInTypeRequest.Objetos.Objeto }
     * 
     */
    public ObtenerObjetoFiltradaInTypeRequest.Objetos.Objeto createObtenerObjetoFiltradaInTypeRequestObjetosObjeto() {
        return new ObtenerObjetoFiltradaInTypeRequest.Objetos.Objeto();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutTypeResponse }
     * 
     */
    public ObtenerObjetoFiltradaOutTypeResponse createObtenerObjetoFiltradaOutTypeResponse() {
        return new ObtenerObjetoFiltradaOutTypeResponse();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutTypeResponse.Relaciones.Relacion }
     * 
     */
    public ObtenerObjetoFiltradaOutTypeResponse.Relaciones.Relacion createObtenerObjetoFiltradaOutTypeResponseRelacionesRelacion() {
        return new ObtenerObjetoFiltradaOutTypeResponse.Relaciones.Relacion();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaInTypeRequest }
     * 
     */
    public ObtenerObjetoFiltradaInTypeRequest createObtenerObjetoFiltradaInTypeRequest() {
        return new ObtenerObjetoFiltradaInTypeRequest();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutTypeResponse.Objetos }
     * 
     */
    public ObtenerObjetoFiltradaOutTypeResponse.Objetos createObtenerObjetoFiltradaOutTypeResponseObjetos() {
        return new ObtenerObjetoFiltradaOutTypeResponse.Objetos();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaInTypeRequest.Objetos }
     * 
     */
    public ObtenerObjetoFiltradaInTypeRequest.Objetos createObtenerObjetoFiltradaInTypeRequestObjetos() {
        return new ObtenerObjetoFiltradaInTypeRequest.Objetos();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerObjetoFiltradaOutTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "ObtenerObjetoFiltradaOutTypeResponse")
    public JAXBElement<ObtenerObjetoFiltradaOutTypeResponse> createObtenerObjetoFiltradaOutTypeResponse(ObtenerObjetoFiltradaOutTypeResponse value) {
        return new JAXBElement<ObtenerObjetoFiltradaOutTypeResponse>(_ObtenerObjetoFiltradaOutTypeResponse_QNAME, ObtenerObjetoFiltradaOutTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGTreintaYDos")
    public JAXBElement<String> createCadenaLGTreintaYDos(String value) {
        return new JAXBElement<String>(_CadenaLGTreintaYDos_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGTreinta")
    public JAXBElement<String> createCadenaLGTreinta(String value) {
        return new JAXBElement<String>(_CadenaLGTreinta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGVeinte")
    public JAXBElement<String> createCadenaLGVeinte(String value) {
        return new JAXBElement<String>(_CadenaLGVeinte_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGSesentaYCuatro")
    public JAXBElement<String> createCadenaLGSesentaYCuatro(String value) {
        return new JAXBElement<String>(_CadenaLGSesentaYCuatro_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerObjetoFiltradaInTypeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "ObtenerObjetoFiltradaInTypeRequest")
    public JAXBElement<ObtenerObjetoFiltradaInTypeRequest> createObtenerObjetoFiltradaInTypeRequest(ObtenerObjetoFiltradaInTypeRequest value) {
        return new JAXBElement<ObtenerObjetoFiltradaInTypeRequest>(_ObtenerObjetoFiltradaInTypeRequest_QNAME, ObtenerObjetoFiltradaInTypeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGDoscientosCincuentaYSeis")
    public JAXBElement<String> createCadenaLGDoscientosCincuentaYSeis(String value) {
        return new JAXBElement<String>(_CadenaLGDoscientosCincuentaYSeis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGOcho")
    public JAXBElement<String> createCadenaLGOcho(String value) {
        return new JAXBElement<String>(_CadenaLGOcho_QNAME, String.class, null, value);
    }

}
