//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.12 at 01:24:27 AM CDT 
//


package com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObtenerObjetoFiltradaIn_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "ObtenerObjetoFiltradaIn");
    private final static QName _CadenaLGTreintaYDos_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGTreintaYDos");
    private final static QName _CadenaLGTreinta_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGTreinta");
    private final static QName _CadenaLGVeinte_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGVeinte");
    private final static QName _CadenaLGSesentaYCuatro_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGSesentaYCuatro");
    private final static QName _CadenaLGDoscientosCincuentaYSeis_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGDoscientosCincuentaYSeis");
    private final static QName _CadenaLGOcho_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "CadenaLGOcho");
    private final static QName _ObtenerObjetoFiltradaOut_QNAME = new QName("http://www.banorte.com/ws/esb/Reconciliaciones", "ObtenerObjetoFiltradaOut");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaInType.Objetos.Objeto }
     * 
     */
    public ObtenerObjetoFiltradaInType.Objetos.Objeto createObtenerObjetoFiltradaInTypeObjetosObjeto() {
        return new ObtenerObjetoFiltradaInType.Objetos.Objeto();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutType.Relaciones }
     * 
     */
    public ObtenerObjetoFiltradaOutType.Relaciones createObtenerObjetoFiltradaOutTypeRelaciones() {
        return new ObtenerObjetoFiltradaOutType.Relaciones();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutType.Relaciones.Relacion }
     * 
     */
    public ObtenerObjetoFiltradaOutType.Relaciones.Relacion createObtenerObjetoFiltradaOutTypeRelacionesRelacion() {
        return new ObtenerObjetoFiltradaOutType.Relaciones.Relacion();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaInType.Objetos }
     * 
     */
    public ObtenerObjetoFiltradaInType.Objetos createObtenerObjetoFiltradaInTypeObjetos() {
        return new ObtenerObjetoFiltradaInType.Objetos();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutType }
     * 
     */
    public ObtenerObjetoFiltradaOutType createObtenerObjetoFiltradaOutType() {
        return new ObtenerObjetoFiltradaOutType();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutType.Objetos }
     * 
     */
    public ObtenerObjetoFiltradaOutType.Objetos createObtenerObjetoFiltradaOutTypeObjetos() {
        return new ObtenerObjetoFiltradaOutType.Objetos();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaInType }
     * 
     */
    public ObtenerObjetoFiltradaInType createObtenerObjetoFiltradaInType() {
        return new ObtenerObjetoFiltradaInType();
    }

    /**
     * Create an instance of {@link ObtenerObjetoFiltradaOutType.Objetos.Objeto }
     * 
     */
    public ObtenerObjetoFiltradaOutType.Objetos.Objeto createObtenerObjetoFiltradaOutTypeObjetosObjeto() {
        return new ObtenerObjetoFiltradaOutType.Objetos.Objeto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerObjetoFiltradaInType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "ObtenerObjetoFiltradaIn")
    public JAXBElement<ObtenerObjetoFiltradaInType> createObtenerObjetoFiltradaIn(ObtenerObjetoFiltradaInType value) {
        return new JAXBElement<ObtenerObjetoFiltradaInType>(_ObtenerObjetoFiltradaIn_QNAME, ObtenerObjetoFiltradaInType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGTreintaYDos")
    public JAXBElement<String> createCadenaLGTreintaYDos(String value) {
        return new JAXBElement<String>(_CadenaLGTreintaYDos_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGTreinta")
    public JAXBElement<String> createCadenaLGTreinta(String value) {
        return new JAXBElement<String>(_CadenaLGTreinta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGVeinte")
    public JAXBElement<String> createCadenaLGVeinte(String value) {
        return new JAXBElement<String>(_CadenaLGVeinte_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGSesentaYCuatro")
    public JAXBElement<String> createCadenaLGSesentaYCuatro(String value) {
        return new JAXBElement<String>(_CadenaLGSesentaYCuatro_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGDoscientosCincuentaYSeis")
    public JAXBElement<String> createCadenaLGDoscientosCincuentaYSeis(String value) {
        return new JAXBElement<String>(_CadenaLGDoscientosCincuentaYSeis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "CadenaLGOcho")
    public JAXBElement<String> createCadenaLGOcho(String value) {
        return new JAXBElement<String>(_CadenaLGOcho_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerObjetoFiltradaOutType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", name = "ObtenerObjetoFiltradaOut")
    public JAXBElement<ObtenerObjetoFiltradaOutType> createObtenerObjetoFiltradaOut(ObtenerObjetoFiltradaOutType value) {
        return new JAXBElement<ObtenerObjetoFiltradaOutType>(_ObtenerObjetoFiltradaOut_QNAME, ObtenerObjetoFiltradaOutType.class, null, value);
    }

}
