//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.12 at 01:24:27 AM CDT 
//


package com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ObtenerObjetoFiltradaOutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObtenerObjetoFiltradaOutType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Objetos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Objeto" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Tran_IdGrupo" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
 *                             &lt;element name="Tran_NombreGrupo" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
 *                             &lt;element name="Tran_IdTipoObjeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
 *                             &lt;element name="Tran_Objeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
 *                             &lt;element name="Tran_Descripcion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
 *                             &lt;element name="Tran_TipoOperacion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGVeinte" minOccurs="0"/>
 *                             &lt;element name="Tran_FechaCreacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="Tran_FechaModificacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="Tran_IdUsuario" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGOcho" minOccurs="0"/>
 *                             &lt;element name="Tran_Extension" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Relaciones" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Tran_IdTipoObjeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
 *                   &lt;element name="Relacion" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Tran_IdPerfil" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
 *                             &lt;element name="Tran_IdTransaccion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
 *                             &lt;element name="Tran_TipoOperacion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGVeinte" minOccurs="0"/>
 *                             &lt;element name="Tran_IdUsuario" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGOcho" minOccurs="0"/>
 *                             &lt;element name="Tran_FechaOperacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObtenerObjetoFiltradaOutType", propOrder = {
    "objetos",
    "relaciones"
})
public class ObtenerObjetoFiltradaOutType {

    @XmlElement(name = "Objetos")
    protected ObtenerObjetoFiltradaOutType.Objetos objetos;
    @XmlElement(name = "Relaciones")
    protected List<ObtenerObjetoFiltradaOutType.Relaciones> relaciones;

    /**
     * Gets the value of the objetos property.
     * 
     * @return
     *     possible object is
     *     {@link ObtenerObjetoFiltradaOutType.Objetos }
     *     
     */
    public ObtenerObjetoFiltradaOutType.Objetos getObjetos() {
        return objetos;
    }

    /**
     * Sets the value of the objetos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObtenerObjetoFiltradaOutType.Objetos }
     *     
     */
    public void setObjetos(ObtenerObjetoFiltradaOutType.Objetos value) {
        this.objetos = value;
    }

    /**
     * Gets the value of the relaciones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relaciones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelaciones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObtenerObjetoFiltradaOutType.Relaciones }
     * 
     * 
     */
    public List<ObtenerObjetoFiltradaOutType.Relaciones> getRelaciones() {
        if (relaciones == null) {
            relaciones = new ArrayList<ObtenerObjetoFiltradaOutType.Relaciones>();
        }
        return this.relaciones;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Objeto" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Tran_IdGrupo" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
     *                   &lt;element name="Tran_NombreGrupo" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
     *                   &lt;element name="Tran_IdTipoObjeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
     *                   &lt;element name="Tran_Objeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
     *                   &lt;element name="Tran_Descripcion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
     *                   &lt;element name="Tran_TipoOperacion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGVeinte" minOccurs="0"/>
     *                   &lt;element name="Tran_FechaCreacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="Tran_FechaModificacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="Tran_IdUsuario" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGOcho" minOccurs="0"/>
     *                   &lt;element name="Tran_Extension" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objeto"
    })
    public static class Objetos {

        @XmlElement(name = "Objeto")
        protected List<ObtenerObjetoFiltradaOutType.Objetos.Objeto> objeto;

        /**
         * Gets the value of the objeto property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objeto property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjeto().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObtenerObjetoFiltradaOutType.Objetos.Objeto }
         * 
         * 
         */
        public List<ObtenerObjetoFiltradaOutType.Objetos.Objeto> getObjeto() {
            if (objeto == null) {
                objeto = new ArrayList<ObtenerObjetoFiltradaOutType.Objetos.Objeto>();
            }
            return this.objeto;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Tran_IdGrupo" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
         *         &lt;element name="Tran_NombreGrupo" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
         *         &lt;element name="Tran_IdTipoObjeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
         *         &lt;element name="Tran_Objeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
         *         &lt;element name="Tran_Descripcion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
         *         &lt;element name="Tran_TipoOperacion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGVeinte" minOccurs="0"/>
         *         &lt;element name="Tran_FechaCreacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="Tran_FechaModificacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="Tran_IdUsuario" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGOcho" minOccurs="0"/>
         *         &lt;element name="Tran_Extension" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGDoscientosCincuentaYSeis" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tranIdGrupo",
            "tranNombreGrupo",
            "tranIdTipoObjeto",
            "tranObjeto",
            "tranDescripcion",
            "tranTipoOperacion",
            "tranFechaCreacion",
            "tranFechaModificacion",
            "tranIdUsuario",
            "tranExtension"
        })
        public static class Objeto {

            @XmlElement(name = "Tran_IdGrupo")
            protected String tranIdGrupo;
            @XmlElement(name = "Tran_NombreGrupo")
            protected String tranNombreGrupo;
            @XmlElement(name = "Tran_IdTipoObjeto")
            protected String tranIdTipoObjeto;
            @XmlElement(name = "Tran_Objeto")
            protected String tranObjeto;
            @XmlElement(name = "Tran_Descripcion")
            protected String tranDescripcion;
            @XmlElement(name = "Tran_TipoOperacion")
            protected String tranTipoOperacion;
            @XmlElement(name = "Tran_FechaCreacion")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar tranFechaCreacion;
            @XmlElement(name = "Tran_FechaModificacion")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar tranFechaModificacion;
            @XmlElement(name = "Tran_IdUsuario")
            protected String tranIdUsuario;
            @XmlElement(name = "Tran_Extension")
            protected String tranExtension;

            /**
             * Gets the value of the tranIdGrupo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranIdGrupo() {
                return tranIdGrupo;
            }

            /**
             * Sets the value of the tranIdGrupo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranIdGrupo(String value) {
                this.tranIdGrupo = value;
            }

            /**
             * Gets the value of the tranNombreGrupo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranNombreGrupo() {
                return tranNombreGrupo;
            }

            /**
             * Sets the value of the tranNombreGrupo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranNombreGrupo(String value) {
                this.tranNombreGrupo = value;
            }

            /**
             * Gets the value of the tranIdTipoObjeto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranIdTipoObjeto() {
                return tranIdTipoObjeto;
            }

            /**
             * Sets the value of the tranIdTipoObjeto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranIdTipoObjeto(String value) {
                this.tranIdTipoObjeto = value;
            }

            /**
             * Gets the value of the tranObjeto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranObjeto() {
                return tranObjeto;
            }

            /**
             * Sets the value of the tranObjeto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranObjeto(String value) {
                this.tranObjeto = value;
            }

            /**
             * Gets the value of the tranDescripcion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranDescripcion() {
                return tranDescripcion;
            }

            /**
             * Sets the value of the tranDescripcion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranDescripcion(String value) {
                this.tranDescripcion = value;
            }

            /**
             * Gets the value of the tranTipoOperacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranTipoOperacion() {
                return tranTipoOperacion;
            }

            /**
             * Sets the value of the tranTipoOperacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranTipoOperacion(String value) {
                this.tranTipoOperacion = value;
            }

            /**
             * Gets the value of the tranFechaCreacion property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTranFechaCreacion() {
                return tranFechaCreacion;
            }

            /**
             * Sets the value of the tranFechaCreacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTranFechaCreacion(XMLGregorianCalendar value) {
                this.tranFechaCreacion = value;
            }

            /**
             * Gets the value of the tranFechaModificacion property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTranFechaModificacion() {
                return tranFechaModificacion;
            }

            /**
             * Sets the value of the tranFechaModificacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTranFechaModificacion(XMLGregorianCalendar value) {
                this.tranFechaModificacion = value;
            }

            /**
             * Gets the value of the tranIdUsuario property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranIdUsuario() {
                return tranIdUsuario;
            }

            /**
             * Sets the value of the tranIdUsuario property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranIdUsuario(String value) {
                this.tranIdUsuario = value;
            }

            /**
             * Gets the value of the tranExtension property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranExtension() {
                return tranExtension;
            }

            /**
             * Sets the value of the tranExtension property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranExtension(String value) {
                this.tranExtension = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tran_IdTipoObjeto" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
     *         &lt;element name="Relacion" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Tran_IdPerfil" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
     *                   &lt;element name="Tran_IdTransaccion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
     *                   &lt;element name="Tran_TipoOperacion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGVeinte" minOccurs="0"/>
     *                   &lt;element name="Tran_IdUsuario" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGOcho" minOccurs="0"/>
     *                   &lt;element name="Tran_FechaOperacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tranIdTipoObjeto",
        "relacion"
    })
    public static class Relaciones {

        @XmlElement(name = "Tran_IdTipoObjeto")
        protected String tranIdTipoObjeto;
        @XmlElement(name = "Relacion")
        protected List<ObtenerObjetoFiltradaOutType.Relaciones.Relacion> relacion;

        /**
         * Gets the value of the tranIdTipoObjeto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranIdTipoObjeto() {
            return tranIdTipoObjeto;
        }

        /**
         * Sets the value of the tranIdTipoObjeto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranIdTipoObjeto(String value) {
            this.tranIdTipoObjeto = value;
        }

        /**
         * Gets the value of the relacion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relacion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelacion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObtenerObjetoFiltradaOutType.Relaciones.Relacion }
         * 
         * 
         */
        public List<ObtenerObjetoFiltradaOutType.Relaciones.Relacion> getRelacion() {
            if (relacion == null) {
                relacion = new ArrayList<ObtenerObjetoFiltradaOutType.Relaciones.Relacion>();
            }
            return this.relacion;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Tran_IdPerfil" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
         *         &lt;element name="Tran_IdTransaccion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGSesentaYCuatro" minOccurs="0"/>
         *         &lt;element name="Tran_TipoOperacion" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGVeinte" minOccurs="0"/>
         *         &lt;element name="Tran_IdUsuario" type="{http://www.banorte.com/ws/esb/Reconciliaciones}CadenaLGOcho" minOccurs="0"/>
         *         &lt;element name="Tran_FechaOperacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tranIdPerfil",
            "tranIdTransaccion",
            "tranTipoOperacion",
            "tranIdUsuario",
            "tranFechaOperacion"
        })
        public static class Relacion {

            @XmlElement(name = "Tran_IdPerfil")
            protected String tranIdPerfil;
            @XmlElement(name = "Tran_IdTransaccion")
            protected String tranIdTransaccion;
            @XmlElement(name = "Tran_TipoOperacion")
            protected String tranTipoOperacion;
            @XmlElement(name = "Tran_IdUsuario")
            protected String tranIdUsuario;
            @XmlElement(name = "Tran_FechaOperacion")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar tranFechaOperacion;

            /**
             * Gets the value of the tranIdPerfil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranIdPerfil() {
                return tranIdPerfil;
            }

            /**
             * Sets the value of the tranIdPerfil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranIdPerfil(String value) {
                this.tranIdPerfil = value;
            }

            /**
             * Gets the value of the tranIdTransaccion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranIdTransaccion() {
                return tranIdTransaccion;
            }

            /**
             * Sets the value of the tranIdTransaccion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranIdTransaccion(String value) {
                this.tranIdTransaccion = value;
            }

            /**
             * Gets the value of the tranTipoOperacion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranTipoOperacion() {
                return tranTipoOperacion;
            }

            /**
             * Sets the value of the tranTipoOperacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranTipoOperacion(String value) {
                this.tranTipoOperacion = value;
            }

            /**
             * Gets the value of the tranIdUsuario property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTranIdUsuario() {
                return tranIdUsuario;
            }

            /**
             * Sets the value of the tranIdUsuario property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTranIdUsuario(String value) {
                this.tranIdUsuario = value;
            }

            /**
             * Gets the value of the tranFechaOperacion property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTranFechaOperacion() {
                return tranFechaOperacion;
            }

            /**
             * Sets the value of the tranFechaOperacion property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTranFechaOperacion(XMLGregorianCalendar value) {
                this.tranFechaOperacion = value;
            }

        }

    }

}
