//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.10 at 09:41:39 p. m. CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema;
