//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.12 at 07:33:43 p.m. CDT 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = { 
        @javax.xml.bind.annotation.XmlNs(prefix = "NS3", namespaceURI="http://www.banorte.com/ws/esb/Reconciliaciones")
    },
	namespace = "http://www.banorte.com/ws/esb/Reconciliaciones", 
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.banorte.ws.esb.reconciliaciones.ObtenerObjeto.filter.schema;
