//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.14 at 02:23:31 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.banorte.com/ws/esb/general/Headers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.banorte.ws.esb.reconciliaciones.requestHeaders.schema;
